# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish -c $(buildConfiguration) -o $(build.stagingdirectory)
  displayName: 'dotnet publish $(buildConfiguration)'
  workingDirectory: $(Build.SourcesDirectory)/Praxeum.WebApp

- task: PublishBuildArtifacts@1
  displayName: 'Publish build output'
  inputs:
    ArtifactName: drop
    PathtoPublish: $(build.stagingdirectory)